INFO - 2022-06-07 08:53:12,233 - process: 28856 - scheduler.py - polls.scheduler - 105 - scheduler - successfully synced task with jobs with force
ERROR - 2022-06-07 10:00:02,871 - process: 28856 - utils.py - polls.utils - 533 - utils - {code: Neo.ClientError.Statement.SyntaxError} {message: Invalid input ')': expected an identifier (line 1, column 19 (offset: 18))
"MATCH relation=(d:)--(node)WHERE d.name = $node_name RETURN relation"
                   ^}
Traceback (most recent call last):
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\polls\utils.py", line 531, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\vr_envver\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\vr_envver\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\vr_envver\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\vr_envver\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\vr_envver\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\vr_envver\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\vr_envver\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\polls\views.py", line 1133, in neo4j_find
    output = app.find_node(label_name, disease_name)
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\polls\neo4jQuery.py", line 62, in find_node
    result = session.read_transaction(self._find_and_return_node, label, disease_name)
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\vr_envver\lib\site-packages\neo4j\work\simple.py", line 396, in read_transaction
    return self._run_transaction(READ_ACCESS, transaction_function, *args, **kwargs)
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\vr_envver\lib\site-packages\neo4j\work\simple.py", line 325, in _run_transaction
    result = transaction_function(tx, *args, **kwargs)
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\polls\neo4jQuery.py", line 84, in _find_and_return_node
    result = tx.run(query, label=label, node_name=node_name)
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\vr_envver\lib\site-packages\neo4j\work\transaction.py", line 137, in run
    result._tx_ready_run(query, parameters, **kwparameters)
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\vr_envver\lib\site-packages\neo4j\work\result.py", line 70, in _tx_ready_run
    self._run(query, parameters, None, None, None, None, **kwparameters)
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\vr_envver\lib\site-packages\neo4j\work\result.py", line 114, in _run
    self._attach()
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\vr_envver\lib\site-packages\neo4j\work\result.py", line 203, in _attach
    self._connection.fetch_message()
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\vr_envver\lib\site-packages\neo4j\io\_common.py", line 186, in inner
    func(*args, **kwargs)
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\vr_envver\lib\site-packages\neo4j\io\_bolt4.py", line 309, in fetch_message
    response.on_failure(summary_metadata or {})
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\vr_envver\lib\site-packages\neo4j\io\_common.py", line 244, in on_failure
    raise Neo4jError.hydrate(**metadata)
neo4j.exceptions.CypherSyntaxError: {code: Neo.ClientError.Statement.SyntaxError} {message: Invalid input ')': expected an identifier (line 1, column 19 (offset: 18))
"MATCH relation=(d:)--(node)WHERE d.name = $node_name RETURN relation"
                   ^}
ERROR - 2022-06-07 11:06:51,819 - process: 28856 - utils.py - polls.utils - 533 - utils - ''
Traceback (most recent call last):
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\polls\utils.py", line 531, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\vr_envver\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\vr_envver\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\vr_envver\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\vr_envver\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\vr_envver\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\vr_envver\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\vr_envver\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\polls\views.py", line 1069, in neo4j_create
    output = app.create_relationship(disease_name, node_label, node_name)
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\polls\neo4jQuery.py", line 22, in create_relationship
    result = session.write_transaction(
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\vr_envver\lib\site-packages\neo4j\work\simple.py", line 421, in write_transaction
    return self._run_transaction(WRITE_ACCESS, transaction_function, *args, **kwargs)
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\vr_envver\lib\site-packages\neo4j\work\simple.py", line 325, in _run_transaction
    result = transaction_function(tx, *args, **kwargs)
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\polls\neo4jQuery.py", line 34, in _create_and_return_relationship
    write_relation = App.label_relation[write_node_label]
KeyError: ''
ERROR - 2022-06-07 11:06:56,965 - process: 28856 - utils.py - polls.utils - 533 - utils - ''
Traceback (most recent call last):
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\polls\utils.py", line 531, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\vr_envver\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\vr_envver\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\vr_envver\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\vr_envver\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\vr_envver\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\vr_envver\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\vr_envver\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\polls\views.py", line 1069, in neo4j_create
    output = app.create_relationship(disease_name, node_label, node_name)
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\polls\neo4jQuery.py", line 22, in create_relationship
    result = session.write_transaction(
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\vr_envver\lib\site-packages\neo4j\work\simple.py", line 421, in write_transaction
    return self._run_transaction(WRITE_ACCESS, transaction_function, *args, **kwargs)
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\vr_envver\lib\site-packages\neo4j\work\simple.py", line 325, in _run_transaction
    result = transaction_function(tx, *args, **kwargs)
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\polls\neo4jQuery.py", line 34, in _create_and_return_relationship
    write_relation = App.label_relation[write_node_label]
KeyError: ''
ERROR - 2022-06-07 11:07:20,346 - process: 28856 - utils.py - polls.utils - 533 - utils - ''
Traceback (most recent call last):
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\polls\utils.py", line 531, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\vr_envver\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\vr_envver\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\vr_envver\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\vr_envver\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\vr_envver\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\vr_envver\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\vr_envver\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\polls\views.py", line 1069, in neo4j_create
    output = app.create_relationship(disease_name, node_label, node_name)
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\polls\neo4jQuery.py", line 22, in create_relationship
    result = session.write_transaction(
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\vr_envver\lib\site-packages\neo4j\work\simple.py", line 421, in write_transaction
    return self._run_transaction(WRITE_ACCESS, transaction_function, *args, **kwargs)
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\vr_envver\lib\site-packages\neo4j\work\simple.py", line 325, in _run_transaction
    result = transaction_function(tx, *args, **kwargs)
  File "C:\Users\46121\PycharmProjects\COMP5703CS65_NLP\polls\neo4jQuery.py", line 34, in _create_and_return_relationship
    write_relation = App.label_relation[write_node_label]
KeyError: ''
